remove ifdef from standalone spirv VUID
KhronosGroup/Vulkan-Docs pull request #1926
Opened 2022-09-01 12:24 UTC by sjfricke

`VUID-StandaloneSpirv-None-04686` is already implemented in SPIR-V Tools and I can add the `TaskPayloadWorkgroupEXT` addition if wanted

2022-09-04 13:12 UTC, sjfricke commented on appendices/spirvenv.adoc
>    * [[VUID-{refpage}-None-04686]]
no need to change the VUID as it has already been updated to include `TaskPayloadWorkgroupEXT`

https://github.com/KhronosGroup/SPIRV-Tools/commit/4c456f7da67c5437a6fb7d4d20d78e2a5ae2acf2#diff-38fd3032d90cb56b9e25b2b4141235b736de1ad8efc70d02dabf2be8adaf0117R211

2022-09-07 13:42 UTC, Tobski commented on appendices/spirvenv.adoc
> +    code:TaskEXT or code:MeshEXT {ExecutionModel} and an entry point that uses
this looks like it's got code: twice?

2022-09-07 13:43 UTC, dgkoch commented on appendices/spirvenv.adoc
> -    *PhysicalStorageBuffer*
extra "or" from above.

2022-09-07 13:44 UTC, oddhack commented
WG will sign off once @TomOlson reviews and approves.

2022-09-07 13:45 UTC, Tobski requested changes
Some editorial changes needed but overall LGTM

2022-09-07 13:45 UTC, Tobski commented on appendices/spirvenv.adoc
>      Class* limited to *Uniform*, *Workgroup*, *Image*, *StorageBuffer*, or
extra `or`

2022-09-07 21:50 UTC, sjfricke commented on appendices/spirvenv.adoc
>      Class* limited to *Uniform*, *Workgroup*, *Image*, *StorageBuffer*, or
```suggestion
    Class* limited to *Uniform*, *Workgroup*, *Image*, *StorageBuffer*,
```

2022-09-07 21:50 UTC, sjfricke commented on appendices/spirvenv.adoc
>      The module must: not contain both an entry point that uses the code:
```suggestion
    The module must: not contain both an entry point that uses the
```

2022-09-08 02:23 UTC, TomOlson approved these changes
LGTM - I had a grammar nit but it's already been fixed. Thanks @sjfricke!

2022-09-08 03:50 UTC, oddhack commented
@tobias I think github may be a little confused - you don't seem to have any outstanding changes requested but your review is still showing that. If I've missed something please bring it up as a separate issue, but going ahead and signing this off for the next spec update.

2022-09-08 03:52 UTC, sjfricke commented
@oddhack he made a PR Change request, I made the change, but I think GitHub still requires the person to manually remove the "request Change" status

2022-09-08 04:46 UTC, oddhack commented
> @oddhack he made a PR Change request, I made the change, but I think GitHub still requires the person to manually remove the "request Change" status

Huh. I am an ever-bigger fan of proposing edits in the comments that can be clicked on to accept and then resolve the issue :-) Not sure the actual 'review' mechanism is that useful for the sort of fine-grained feedback we tend to get vs. just accepting their edits and them approving, but there doesn't seem to be a gitlab-like 'approve' button yet :-(

2022-09-08 05:35 UTC, merged